name: NGINX Deployment

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Your build and deployment commands here
          echo "Building and deploying NGINX..."

  manual-approval:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        run: |
          PR_URL=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"head": "${{ github.sha }}", "base": "prod", "title": "Manual Approval", "body": "Please review the NGINX deployment changes and approve."}' \
            | jq -r .url)

          echo "::set-output name=pr_url::$PR_URL"

      - name: Wait for Approval
        id: approval
        run: |
          while true; do
            STATE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ steps.manual-approval.outputs.pr_url }} | jq -r .state)
            if [ "$STATE" == "closed" ]; then
              echo "Pull request closed. Exiting."
              exit 1
            elif [ "$STATE" == "open" ]; then
              echo "Pull request still open. Waiting..."
              sleep 10
            elif [ "$STATE" == "merged" ]; then
              echo "Pull request merged. Continuing..."
              break
            else
              echo "Unknown pull request state. Exiting."
              exit 1
            fi
          done

          APPROVAL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ steps.manual-approval.outputs.pr_url }}/reviews | jq -r '.[] | select(.state=="APPROVED")')
          if [ -z "$APPROVAL" ]; then
            echo "No approvals found. Exiting."
            exit 1
          fi

          echo "::set-output name=approved::true"

      - name: Check Approval
        run: |
          if [ "${{ steps.approval.outputs.approved }}" != "true" ]; then
            echo "Manual approval not granted. Exiting."
            exit 1
          fi

  deploy:
    needs: manual-approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy NGINX
        run: |
          # Your deployment commands here
          echo "Deploying NGINX..."
