name: NGINX Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Your build and deployment commands here
          echo "Building and deploying NGINX..."

  manual-approval:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: 'your-github-username'
          minimum-approvals: 1
          issue-title: 'Review and Approve NGINX Deployment'
          issue-body: 'Please review the NGINX deployment changes and approve.'

  deploy:
    needs: manual-approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy NGINX
        run: |
          # Your deployment commands here
          echo "Deploying NGINX..."



# name: Manual Trigger and release pipeline

# on:
#   workflow_dispatch:
#     branches:
#       - prod

# jobs:
#   job_1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: My first step
#         run: echo This is the first step of my first job.
#       - uses: vprinshad/tesing.git@v1
#         with:
#           approvers: 'vprinshad'  # Replace with the actual team name
#           minimum-approvals: 1
#           issue-title: 'Review and Approve Deployment'
#           issue-body: 'Please review the changes and approve the deployment to production.'

