name: NGINX Deployment

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Your build and deployment commands here
          echo "Building and deploying NGINX..."

  manual-approval:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        uses: actions/github-script@v4
        with:
          script: |
            const github = context.github;
            const { data } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Manual Approval',
              head: context.sha,
              base: 'prod',
              body: 'Please review the NGINX deployment changes and approve.',
            });
            core.setOutput('pull_request_number', data.number);

      - name: Wait for Approval
        id: approval
        uses: actions/github-script@v4
        with:
          script: |
            const github = context.github;
            const { data } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            core.setOutput('approved', data.state === 'approved');

      - name: Check Approval
        run: |
          if [ "${{ steps.approval.outputs.approved }}" != "true" ]; then
            echo "Manual approval not granted. Exiting."
            exit 1
          fi

  deploy:
    needs: manual-approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy NGINX
        run: |
          # Your deployment commands here
          echo "Deploying NGINX..."
