name: NGINX Deployment

on:
  push:
    branches:
      - prod

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: vprinshad/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: trstringer,vprinshad,sharoon001
      - name: Deploy to production
        run: echo deploying
