name: Manual Trigger and release pipeline

on:
  workflow_dispatch:
    branches:
      - prod

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo This is the first step of my first job.
      - uses: vprinshad/manual-approval@v1
        with:
          approvers: 'testing'  # Replace with the actual team name
          minimum-approvals: 1
          issue-title: 'Review and Approve Deployment'
          issue-body: 'Please review the changes and approve the deployment to production.'
